#!/usr/bin/env python3
"""
build_site.py

Builds a static site (docs/) from the raw journal entries (journal/*.md),
organized as a browsable date archive -- meant to be served via GitHub
Pages (Settings -> Pages -> Deploy from branch -> /docs).

Deliberately dependency-free (no `markdown` pip package): the journal
entries are generated by our own ecc_journal.py with a small, known set
of Markdown patterns (headers, bold, italic, links, code fences,
horizontal rules, paragraphs), so a small hand-written converter is
enough and keeps the whole project pip-install-free.

Usage:
    python3 scripts/build_site.py
    (regenerates docs/ entirely from journal/*.md -- safe to re-run)
"""

import glob
import html
import os
import re

JOURNAL_DIR = "journal"
DOCS_DIR = "docs"

CSS = """
:root { color-scheme: light dark; }
body {
  max-width: 780px; margin: 2rem auto; padding: 0 1rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  line-height: 1.55;
}
h1 { font-size: 1.6rem; margin-bottom: 0.25rem; }
h2 { font-size: 1.2rem; margin-top: 2rem; border-bottom: 1px solid #8883; padding-bottom: 0.3rem; }
h3 { font-size: 1.05rem; margin-top: 1.5rem; }
nav.top { margin-bottom: 1.5rem; font-size: 0.9rem; }
nav.top a { margin-right: 1rem; }
code, pre { background: #80808022; border-radius: 4px; }
pre { padding: 0.75rem; overflow-x: auto; font-size: 0.85rem; }
code { padding: 0.1rem 0.3rem; }
pre code { padding: 0; background: none; }
.archive-year { margin-top: 1.5rem; font-weight: 600; }
.archive-list { list-style: none; padding-left: 0; }
.archive-list li { padding: 0.15rem 0; }
.archive-list a { text-decoration: none; }
.archive-list a:hover { text-decoration: underline; }
.meta { color: #888; font-size: 0.9rem; }
hr { border: none; border-top: 1px solid #8883; margin: 1.5rem 0; }
footer { margin-top: 3rem; font-size: 0.85rem; color: #888; }
"""

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<nav class="top"><a href="{root}index.html">Index</a><a href="{root}archive.html">Full archive</a></nav>
{body}
<footer>Generated by <code>scripts/build_site.py</code> from <code>journal/*.md</code>.</footer>
</body>
</html>
"""


def md_to_html(text):
    """Minimal Markdown -> HTML for the specific subset ecc_journal.py
    generates: #/##/### headers, **bold**, _italic_, [text](url) links,
    ```fenced code blocks```, --- horizontal rules, blank-line paragraphs."""
    lines = text.split("\n")
    out = []
    in_code = False
    code_buf = []
    para_buf = []

    def flush_para():
        if para_buf:
            joined = " ".join(para_buf).strip()
            if joined:
                out.append(f"<p>{inline(joined)}</p>")
            para_buf.clear()

    def inline(s):
        s = html.escape(s, quote=False)
        s = re.sub(r"`([^`]+?)`", r"<code>\1</code>", s)
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<em>\1</em>", s)
        s = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"<em>\1</em>", s)
        s = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', s)
        return s

    in_list = False

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for line in lines:
        if line.strip().startswith("```"):
            if in_code:
                out.append("<pre><code>" + html.escape("\n".join(code_buf)) + "</code></pre>")
                code_buf = []
                in_code = False
            else:
                flush_para()
                close_list()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue

        stripped = line.strip()
        if stripped == "":
            flush_para()
            close_list()
            continue
        if stripped == "---":
            flush_para()
            close_list()
            out.append("<hr>")
            continue
        m = re.match(r"^(#{1,3})\s+(.*)", stripped)
        if m:
            flush_para()
            close_list()
            level = len(m.group(1))
            out.append(f"<h{level}>{inline(m.group(2))}</h{level}>")
            continue
        bullet = re.match(r"^[-*]\s+(.*)", stripped)
        if bullet:
            flush_para()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{inline(bullet.group(1))}</li>")
            continue
        close_list()
        para_buf.append(stripped)

    flush_para()
    close_list()
    return "\n".join(out)


def parse_date_from_filename(path):
    """journal/2026-08-25.md -> '2026-08-25'; journal/2026-08-25_recent_sample.md
    -> also '2026-08-25' (sorts alongside the main entry for that day)."""
    base = os.path.basename(path)[:-3]  # strip .md
    m = re.match(r"(\d{4}-\d{2}-\d{2})", base)
    return m.group(1) if m else base, base


def build():
    os.makedirs(DOCS_DIR, exist_ok=True)
    os.makedirs(os.path.join(DOCS_DIR, "entries"), exist_ok=True)

    with open(os.path.join(DOCS_DIR, "style.css"), "w", encoding="utf-8") as f:
        f.write(CSS)

    md_files = glob.glob(os.path.join(JOURNAL_DIR, "*.md"))
    entries = []  # (date, slug, title, path, is_primary)

    for path in md_files:
        date, slug = parse_date_from_filename(path)
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        first_line = text.split("\n", 1)[0].lstrip("# ").strip()
        title = first_line or slug
        is_primary = (slug == date)  # "2026-08-25.md" vs "2026-08-25_recent_sample.md"

        body_html = md_to_html(text)
        out_name = f"{slug}.html"
        out_path = os.path.join(DOCS_DIR, "entries", out_name)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(PAGE_TEMPLATE.format(title=title, css=CSS, root="../", body=body_html))

        entries.append((date, slug, title, f"entries/{out_name}", is_primary))

    # Sort so that, within the same date, the primary dated entry
    # (e.g. "2026-08-25.md") comes before any supplementary files for
    # that same date (e.g. "2026-08-25_recent_sample.md") -- a plain
    # filename string-sort would put "_recent_sample" first (since '_'
    # sorts after '.' in ASCII), which picked the wrong file as
    # "latest" for the homepage. Confirmed and fixed after inspecting
    # the actual generated index.html.
    # date descending, and within the same date: primary (True) before
    # supplementary (False) -- both wanted "descending", so both fields
    # go the same direction under a single reverse=True (True=1 sorts
    # before False=0 that way, which is what we want for is_primary).
    entries.sort(key=lambda e: (e[0], e[4]), reverse=True)
    md_files = [os.path.join(JOURNAL_DIR, f"{e[1]}.md") for e in entries]

    # --- archive page, grouped by year/month ---
    by_year_month = {}
    for date, slug, title, rel, is_primary in entries:
        year, month = date[:4], date[5:7]
        by_year_month.setdefault(year, {}).setdefault(month, []).append((date, slug, title, rel, is_primary))

    archive_body = ["<h1>Full archive</h1>"]
    for year in sorted(by_year_month, reverse=True):
        archive_body.append(f'<div class="archive-year">{year}</div>')
        months = by_year_month[year]
        for month in sorted(months, reverse=True):
            archive_body.append("<ul class='archive-list'>")
            # same (date, is_primary) ordering as the top-level sort,
            # so the primary dated entry always lists before any
            # supplementary entries sharing that date
            for date, slug, title, rel, is_primary in sorted(months[month], key=lambda e: (e[0], e[4]), reverse=True):
                archive_body.append(f'<li><span class="meta">{date}</span> — <a href="{rel}">{html.escape(title)}</a></li>')
            archive_body.append("</ul>")

    with open(os.path.join(DOCS_DIR, "archive.html"), "w", encoding="utf-8") as f:
        f.write(PAGE_TEMPLATE.format(title="Archive — ECC Journal", css=CSS, root="", body="\n".join(archive_body)))

    # --- index page: latest entry inline + short recent list ---
    index_body = ["<h1>Error-Correcting-Code Journal</h1>",
                  '<p class="meta">A daily-updated log of arXiv error-correcting-code papers, '
                  'split by whether their code is publicly available.</p>']
    if entries:
        latest_date, latest_slug, latest_title, latest_rel, _ = entries[0]
        with open(md_files[0], "r", encoding="utf-8") as f:
            latest_text = f.read()
        index_body.append("<hr>")
        index_body.append(f'<p class="meta">Latest entry: {latest_date}</p>')
        index_body.append(md_to_html(latest_text))
        index_body.append("<hr>")
        index_body.append("<h2>Recent entries</h2><ul class='archive-list'>")
        for date, slug, title, rel, _ in entries[1:11]:
            index_body.append(f'<li><span class="meta">{date}</span> — <a href="{rel}">{html.escape(title)}</a></li>')
        index_body.append("</ul>")
        index_body.append('<p><a href="archive.html">See the full archive by date &rarr;</a></p>')
    else:
        index_body.append("<p>No entries yet.</p>")

    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(PAGE_TEMPLATE.format(title="ECC Journal", css=CSS, root="", body="\n".join(index_body)))

    print(f"Built {len(entries)} entr{'y' if len(entries)==1 else 'ies'} into {DOCS_DIR}/")


if __name__ == "__main__":
    build()
